# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'battle_simulator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabCreate = QtWidgets.QTabWidget(self.centralwidget)
        self.tabCreate.setGeometry(QtCore.QRect(0, 0, 1071, 531))
        self.tabCreate.setObjectName("tabCreate")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.viewPokemon1 = QtWidgets.QGraphicsView(self.tab)
        self.viewPokemon1.setGeometry(QtCore.QRect(10, 30, 256, 151))
        self.viewPokemon1.setObjectName("viewPokemon1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(-80, 0, 201, 31))
        self.label.setObjectName("label")
        self.listPokemon1_moves = QtWidgets.QListWidget(self.tab)
        self.listPokemon1_moves.setGeometry(QtCore.QRect(0, 240, 321, 81))
        self.listPokemon1_moves.setObjectName("listPokemon1_moves")
        item = QtWidgets.QListWidgetItem()
        self.listPokemon1_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon1_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon1_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon1_moves.addItem(item)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(390, 60, 201, 31))
        self.label_3.setObjectName("label_3")
        self.viewPokemon2 = QtWidgets.QGraphicsView(self.tab)
        self.viewPokemon2.setGeometry(QtCore.QRect(810, 30, 256, 151))
        self.viewPokemon2.setObjectName("viewPokemon2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(720, 0, 201, 31))
        self.label_2.setObjectName("label_2")
        self.listPokemon2_moves = QtWidgets.QListWidget(self.tab)
        self.listPokemon2_moves.setGeometry(QtCore.QRect(740, 240, 321, 81))
        self.listPokemon2_moves.setObjectName("listPokemon2_moves")
        item = QtWidgets.QListWidgetItem()
        self.listPokemon2_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon2_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon2_moves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listPokemon2_moves.addItem(item)
        self.pushStartBattle = QtWidgets.QPushButton(self.tab)
        self.pushStartBattle.setGeometry(QtCore.QRect(340, 50, 92, 27))
        self.pushStartBattle.setObjectName("pushStartBattle")
        self.pushRestart = QtWidgets.QPushButton(self.tab)
        self.pushRestart.setGeometry(QtCore.QRect(630, 50, 92, 27))
        self.pushRestart.setObjectName("pushRestart")
        self.pushDifferentTeam = QtWidgets.QPushButton(self.tab)
        self.pushDifferentTeam.setGeometry(QtCore.QRect(430, 10, 201, 27))
        self.pushDifferentTeam.setObjectName("pushDifferentTeam")
        self.label_190 = QtWidgets.QLabel(self.tab)
        self.label_190.setGeometry(QtCore.QRect(0, 340, 111, 31))
        self.label_190.setObjectName("label_190")
        self.listPlayer1_team = QtWidgets.QListWidget(self.tab)
        self.listPlayer1_team.setGeometry(QtCore.QRect(0, 370, 321, 81))
        self.listPlayer1_team.setObjectName("listPlayer1_team")
        self.label_191 = QtWidgets.QLabel(self.tab)
        self.label_191.setGeometry(QtCore.QRect(260, 0, 41, 31))
        self.label_191.setObjectName("label_191")
        self.label_192 = QtWidgets.QLabel(self.tab)
        self.label_192.setGeometry(QtCore.QRect(720, 0, 41, 31))
        self.label_192.setObjectName("label_192")
        self.txtPokemon1_Level = QtWidgets.QLineEdit(self.tab)
        self.txtPokemon1_Level.setGeometry(QtCore.QRect(300, 0, 41, 31))
        self.txtPokemon1_Level.setObjectName("txtPokemon1_Level")
        self.txtPokemon2_Level = QtWidgets.QLineEdit(self.tab)
        self.txtPokemon2_Level.setGeometry(QtCore.QRect(760, 0, 41, 31))
        self.txtPokemon2_Level.setObjectName("txtPokemon2_Level")
        self.label_230 = QtWidgets.QLabel(self.tab)
        self.label_230.setGeometry(QtCore.QRect(740, 340, 111, 31))
        self.label_230.setObjectName("label_230")
        self.listPlayer2_team = QtWidgets.QListWidget(self.tab)
        self.listPlayer2_team.setGeometry(QtCore.QRect(740, 370, 321, 81))
        self.listPlayer2_team.setObjectName("listPlayer2_team")
        self.lbl_hpPokemon1 = QtWidgets.QLabel(self.tab)
        self.lbl_hpPokemon1.setGeometry(QtCore.QRect(10, 180, 21, 31))
        self.lbl_hpPokemon1.setObjectName("lbl_hpPokemon1")
        self.lbl_hpPokemon2 = QtWidgets.QLabel(self.tab)
        self.lbl_hpPokemon2.setGeometry(QtCore.QRect(810, 180, 41, 31))
        self.lbl_hpPokemon2.setObjectName("lbl_hpPokemon2")
        self.pushSwitchPlayer1 = QtWidgets.QPushButton(self.tab)
        self.pushSwitchPlayer1.setGeometry(QtCore.QRect(110, 340, 92, 27))
        self.pushSwitchPlayer1.setObjectName("pushSwitchPlayer1")
        self.pushSwitchPlayer2 = QtWidgets.QPushButton(self.tab)
        self.pushSwitchPlayer2.setGeometry(QtCore.QRect(850, 340, 92, 27))
        self.pushSwitchPlayer2.setObjectName("pushSwitchPlayer2")
        self.hpBar_Pokemon1 = QtWidgets.QProgressBar(self.tab)
        self.hpBar_Pokemon1.setGeometry(QtCore.QRect(40, 180, 118, 23))
        self.hpBar_Pokemon1.setProperty("value", 24)
        self.hpBar_Pokemon1.setObjectName("hpBar_Pokemon1")
        self.hpBar_Pokemon2 = QtWidgets.QProgressBar(self.tab)
        self.hpBar_Pokemon2.setGeometry(QtCore.QRect(840, 180, 118, 23))
        self.hpBar_Pokemon2.setProperty("value", 24)
        self.hpBar_Pokemon2.setObjectName("hpBar_Pokemon2")
        self.txtBattleInfo = QtWidgets.QTextEdit(self.tab)
        self.txtBattleInfo.setGeometry(QtCore.QRect(340, 90, 381, 211))
        self.txtBattleInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtBattleInfo.setObjectName("txtBattleInfo")
        self.lbl_statusPokemon1 = QtWidgets.QLabel(self.tab)
        self.lbl_statusPokemon1.setGeometry(QtCore.QRect(10, 200, 51, 31))
        self.lbl_statusPokemon1.setObjectName("lbl_statusPokemon1")
        self.lbl_statusCond1 = QtWidgets.QLabel(self.tab)
        self.lbl_statusCond1.setGeometry(QtCore.QRect(60, 200, 51, 31))
        self.lbl_statusCond1.setObjectName("lbl_statusCond1")
        self.lbl_statusPokemon2 = QtWidgets.QLabel(self.tab)
        self.lbl_statusPokemon2.setGeometry(QtCore.QRect(810, 200, 51, 31))
        self.lbl_statusPokemon2.setObjectName("lbl_statusPokemon2")
        self.lbl_statusCond2 = QtWidgets.QLabel(self.tab)
        self.lbl_statusCond2.setGeometry(QtCore.QRect(860, 200, 51, 31))
        self.lbl_statusCond2.setObjectName("lbl_statusCond2")
        self.tabCreate.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 201, 17))
        self.label_4.setObjectName("label_4")
        self.comboBattleType = QtWidgets.QComboBox(self.tab_2)
        self.comboBattleType.setGeometry(QtCore.QRect(10, 30, 141, 27))
        self.comboBattleType.setObjectName("comboBattleType")
        self.comboBattleType.addItem("")
        self.comboBattleType.addItem("")
        self.comboBattleType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 130, 201, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 31, 17))
        self.label_6.setObjectName("label_6")
        self.txtPokedexEntry = QtWidgets.QLineEdit(self.tab_2)
        self.txtPokedexEntry.setGeometry(QtCore.QRect(60, 170, 151, 27))
        self.txtPokedexEntry.setObjectName("txtPokedexEntry")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(0, 230, 201, 17))
        self.label_7.setObjectName("label_7")
        self.viewCurrentPokemon = QtWidgets.QGraphicsView(self.tab_2)
        self.viewCurrentPokemon.setGeometry(QtCore.QRect(0, 250, 241, 171))
        self.viewCurrentPokemon.setObjectName("viewCurrentPokemon")
        self.comboAvailableMoves = QtWidgets.QComboBox(self.tab_2)
        self.comboAvailableMoves.setGeometry(QtCore.QRect(260, 280, 141, 27))
        self.comboAvailableMoves.setObjectName("comboAvailableMoves")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(260, 260, 201, 17))
        self.label_8.setObjectName("label_8")
        self.listChosenMoves = QtWidgets.QListWidget(self.tab_2)
        self.listChosenMoves.setGeometry(QtCore.QRect(260, 360, 321, 81))
        self.listChosenMoves.setObjectName("listChosenMoves")
        item = QtWidgets.QListWidgetItem()
        self.listChosenMoves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChosenMoves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChosenMoves.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChosenMoves.addItem(item)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(260, 340, 201, 17))
        self.label_9.setObjectName("label_9")
        self.txtChosenLevel = QtWidgets.QLineEdit(self.tab_2)
        self.txtChosenLevel.setGeometry(QtCore.QRect(60, 200, 51, 27))
        self.txtChosenLevel.setObjectName("txtChosenLevel")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 41, 17))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(260, 40, 31, 17))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(260, 60, 41, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(260, 80, 61, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(260, 100, 101, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(260, 120, 111, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(260, 140, 41, 17))
        self.label_16.setObjectName("label_16")
        self.txtEV_HP = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_HP.setGeometry(QtCore.QRect(380, 40, 51, 16))
        self.txtEV_HP.setObjectName("txtEV_HP")
        self.txtEV_Attack = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_Attack.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.txtEV_Attack.setObjectName("txtEV_Attack")
        self.txtEV_Defense = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_Defense.setGeometry(QtCore.QRect(380, 80, 51, 16))
        self.txtEV_Defense.setObjectName("txtEV_Defense")
        self.txtEV_SpAttack = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_SpAttack.setGeometry(QtCore.QRect(380, 100, 51, 16))
        self.txtEV_SpAttack.setObjectName("txtEV_SpAttack")
        self.txtEV_SpDefense = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_SpDefense.setGeometry(QtCore.QRect(380, 120, 51, 16))
        self.txtEV_SpDefense.setObjectName("txtEV_SpDefense")
        self.txtEV_Speed = QtWidgets.QLineEdit(self.tab_2)
        self.txtEV_Speed.setGeometry(QtCore.QRect(380, 140, 51, 16))
        self.txtEV_Speed.setObjectName("txtEV_Speed")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(510, 10, 31, 17))
        self.label_65.setObjectName("label_65")
        self.label_100 = QtWidgets.QLabel(self.tab_2)
        self.label_100.setGeometry(QtCore.QRect(510, 40, 31, 17))
        self.label_100.setObjectName("label_100")
        self.txtIV_HP = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_HP.setGeometry(QtCore.QRect(640, 40, 51, 16))
        self.txtIV_HP.setObjectName("txtIV_HP")
        self.label_101 = QtWidgets.QLabel(self.tab_2)
        self.label_101.setGeometry(QtCore.QRect(510, 60, 41, 17))
        self.label_101.setObjectName("label_101")
        self.txtIV_Attack = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_Attack.setGeometry(QtCore.QRect(640, 60, 51, 16))
        self.txtIV_Attack.setObjectName("txtIV_Attack")
        self.label_102 = QtWidgets.QLabel(self.tab_2)
        self.label_102.setGeometry(QtCore.QRect(510, 80, 61, 17))
        self.label_102.setObjectName("label_102")
        self.txtIV_Defense = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_Defense.setGeometry(QtCore.QRect(640, 80, 51, 16))
        self.txtIV_Defense.setObjectName("txtIV_Defense")
        self.label_103 = QtWidgets.QLabel(self.tab_2)
        self.label_103.setGeometry(QtCore.QRect(510, 100, 101, 17))
        self.label_103.setObjectName("label_103")
        self.txtIV_SpAttack = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_SpAttack.setGeometry(QtCore.QRect(640, 100, 51, 16))
        self.txtIV_SpAttack.setObjectName("txtIV_SpAttack")
        self.label_104 = QtWidgets.QLabel(self.tab_2)
        self.label_104.setGeometry(QtCore.QRect(510, 120, 111, 17))
        self.label_104.setObjectName("label_104")
        self.txtIV_SpDefense = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_SpDefense.setGeometry(QtCore.QRect(640, 120, 51, 16))
        self.txtIV_SpDefense.setObjectName("txtIV_SpDefense")
        self.label_127 = QtWidgets.QLabel(self.tab_2)
        self.label_127.setGeometry(QtCore.QRect(510, 140, 41, 17))
        self.label_127.setObjectName("label_127")
        self.txtIV_Speed = QtWidgets.QLineEdit(self.tab_2)
        self.txtIV_Speed.setGeometry(QtCore.QRect(640, 140, 51, 16))
        self.txtIV_Speed.setObjectName("txtIV_Speed")
        self.pushRandomizeEVs = QtWidgets.QPushButton(self.tab_2)
        self.pushRandomizeEVs.setGeometry(QtCore.QRect(260, 170, 92, 27))
        self.pushRandomizeEVs.setObjectName("pushRandomizeEVs")
        self.pushRandomizeIVs = QtWidgets.QPushButton(self.tab_2)
        self.pushRandomizeIVs.setGeometry(QtCore.QRect(510, 170, 92, 27))
        self.pushRandomizeIVs.setObjectName("pushRandomizeIVs")
        self.label_128 = QtWidgets.QLabel(self.tab_2)
        self.label_128.setGeometry(QtCore.QRect(20, 150, 201, 17))
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.tab_2)
        self.label_129.setGeometry(QtCore.QRect(840, 10, 131, 17))
        self.label_129.setObjectName("label_129")
        self.label_155 = QtWidgets.QLabel(self.tab_2)
        self.label_155.setGeometry(QtCore.QRect(840, 40, 31, 17))
        self.label_155.setObjectName("label_155")
        self.txtFinal_HP = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_HP.setGeometry(QtCore.QRect(950, 40, 51, 16))
        self.txtFinal_HP.setObjectName("txtFinal_HP")
        self.label_182 = QtWidgets.QLabel(self.tab_2)
        self.label_182.setGeometry(QtCore.QRect(840, 60, 41, 17))
        self.label_182.setObjectName("label_182")
        self.txtFinal_Attack = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_Attack.setGeometry(QtCore.QRect(950, 60, 51, 16))
        self.txtFinal_Attack.setObjectName("txtFinal_Attack")
        self.label_183 = QtWidgets.QLabel(self.tab_2)
        self.label_183.setGeometry(QtCore.QRect(840, 80, 61, 17))
        self.label_183.setObjectName("label_183")
        self.txtFinal_Defense = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_Defense.setGeometry(QtCore.QRect(950, 80, 51, 16))
        self.txtFinal_Defense.setObjectName("txtFinal_Defense")
        self.label_184 = QtWidgets.QLabel(self.tab_2)
        self.label_184.setGeometry(QtCore.QRect(840, 100, 101, 17))
        self.label_184.setObjectName("label_184")
        self.txtFinal_SpAttack = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_SpAttack.setGeometry(QtCore.QRect(950, 100, 51, 16))
        self.txtFinal_SpAttack.setObjectName("txtFinal_SpAttack")
        self.label_185 = QtWidgets.QLabel(self.tab_2)
        self.label_185.setGeometry(QtCore.QRect(840, 120, 111, 17))
        self.label_185.setObjectName("label_185")
        self.txtFinal_SpDefense = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_SpDefense.setGeometry(QtCore.QRect(950, 120, 51, 16))
        self.txtFinal_SpDefense.setObjectName("txtFinal_SpDefense")
        self.label_186 = QtWidgets.QLabel(self.tab_2)
        self.label_186.setGeometry(QtCore.QRect(840, 140, 41, 17))
        self.label_186.setObjectName("label_186")
        self.txtFinal_Speed = QtWidgets.QLineEdit(self.tab_2)
        self.txtFinal_Speed.setGeometry(QtCore.QRect(950, 140, 51, 16))
        self.txtFinal_Speed.setObjectName("txtFinal_Speed")
        self.label_187 = QtWidgets.QLabel(self.tab_2)
        self.label_187.setGeometry(QtCore.QRect(600, 210, 201, 17))
        self.label_187.setObjectName("label_187")
        self.label_188 = QtWidgets.QLabel(self.tab_2)
        self.label_188.setGeometry(QtCore.QRect(860, 210, 201, 17))
        self.label_188.setObjectName("label_188")
        self.pushClearP1 = QtWidgets.QPushButton(self.tab_2)
        self.pushClearP1.setGeometry(QtCore.QRect(600, 350, 92, 27))
        self.pushClearP1.setObjectName("pushClearP1")
        self.pushClearP2 = QtWidgets.QPushButton(self.tab_2)
        self.pushClearP2.setGeometry(QtCore.QRect(860, 350, 92, 27))
        self.pushClearP2.setObjectName("pushClearP2")
        self.pushDone = QtWidgets.QPushButton(self.tab_2)
        self.pushDone.setGeometry(QtCore.QRect(750, 390, 92, 27))
        self.pushDone.setObjectName("pushDone")
        self.label_189 = QtWidgets.QLabel(self.tab_2)
        self.label_189.setGeometry(QtCore.QRect(0, 70, 211, 17))
        self.label_189.setObjectName("label_189")
        self.comboPlayerNumber = QtWidgets.QComboBox(self.tab_2)
        self.comboPlayerNumber.setGeometry(QtCore.QRect(10, 90, 141, 27))
        self.comboPlayerNumber.setObjectName("comboPlayerNumber")
        self.comboPlayerNumber.addItem("")
        self.comboPlayerNumber.addItem("")
        self.comboPlayerNumber.addItem("")
        self.label_234 = QtWidgets.QLabel(self.tab_2)
        self.label_234.setGeometry(QtCore.QRect(430, 260, 121, 17))
        self.label_234.setObjectName("label_234")
        self.comboAvailableAbilities = QtWidgets.QComboBox(self.tab_2)
        self.comboAvailableAbilities.setGeometry(QtCore.QRect(430, 280, 141, 27))
        self.comboAvailableAbilities.setObjectName("comboAvailableAbilities")
        self.label_235 = QtWidgets.QLabel(self.tab_2)
        self.label_235.setGeometry(QtCore.QRect(260, 230, 51, 17))
        self.label_235.setObjectName("label_235")
        self.comboNatures = QtWidgets.QComboBox(self.tab_2)
        self.comboNatures.setGeometry(QtCore.QRect(310, 220, 81, 27))
        self.comboNatures.setObjectName("comboNatures")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.comboNatures.addItem("")
        self.labelLevelCheck = QtWidgets.QLabel(self.tab_2)
        self.labelLevelCheck.setGeometry(QtCore.QRect(110, 230, 131, 20))
        self.labelLevelCheck.setText("")
        self.labelLevelCheck.setObjectName("labelLevelCheck")
        self.labelEntryCheck = QtWidgets.QLabel(self.tab_2)
        self.labelEntryCheck.setGeometry(QtCore.QRect(130, 200, 131, 20))
        self.labelEntryCheck.setText("")
        self.labelEntryCheck.setObjectName("labelEntryCheck")
        self.labelEVCheck = QtWidgets.QLabel(self.tab_2)
        self.labelEVCheck.setGeometry(QtCore.QRect(300, 10, 131, 20))
        self.labelEVCheck.setText("")
        self.labelEVCheck.setObjectName("labelEVCheck")
        self.labelIVCheck = QtWidgets.QLabel(self.tab_2)
        self.labelIVCheck.setGeometry(QtCore.QRect(560, 10, 131, 20))
        self.labelIVCheck.setText("")
        self.labelIVCheck.setObjectName("labelIVCheck")
        self.pushFinished = QtWidgets.QPushButton(self.tab_2)
        self.pushFinished.setGeometry(QtCore.QRect(700, 170, 131, 27))
        self.pushFinished.setObjectName("pushFinished")
        self.labelCheckFinalized = QtWidgets.QLabel(self.tab_2)
        self.labelCheckFinalized.setGeometry(QtCore.QRect(700, 150, 131, 17))
        self.labelCheckFinalized.setText("")
        self.labelCheckFinalized.setObjectName("labelCheckFinalized")
        self.listCurr_p1Team = QtWidgets.QListWidget(self.tab_2)
        self.listCurr_p1Team.setGeometry(QtCore.QRect(600, 230, 161, 111))
        self.listCurr_p1Team.setObjectName("listCurr_p1Team")
        self.listCurr_p2Team = QtWidgets.QListWidget(self.tab_2)
        self.listCurr_p2Team.setGeometry(QtCore.QRect(840, 230, 161, 111))
        self.listCurr_p2Team.setObjectName("listCurr_p2Team")
        self.labelChk_Play = QtWidgets.QLabel(self.tab_2)
        self.labelChk_Play.setGeometry(QtCore.QRect(730, 360, 121, 17))
        self.labelChk_Play.setText("")
        self.labelChk_Play.setObjectName("labelChk_Play")
        self.label_239 = QtWidgets.QLabel(self.tab_2)
        self.label_239.setGeometry(QtCore.QRect(420, 230, 51, 17))
        self.label_239.setObjectName("label_239")
        self.comboItems = QtWidgets.QComboBox(self.tab_2)
        self.comboItems.setGeometry(QtCore.QRect(460, 220, 104, 26))
        self.comboItems.setObjectName("comboItems")
        self.pushAddMove = QtWidgets.QPushButton(self.tab_2)
        self.pushAddMove.setGeometry(QtCore.QRect(260, 310, 101, 31))
        self.pushAddMove.setObjectName("pushAddMove")
        self.txtHappinessVal = QtWidgets.QLineEdit(self.tab_2)
        self.txtHappinessVal.setGeometry(QtCore.QRect(200, 200, 51, 27))
        self.txtHappinessVal.setObjectName("txtHappinessVal")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(130, 200, 71, 17))
        self.label_17.setObjectName("label_17")
        self.tabCreate.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabCreate.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.viewPokemon2, self.viewPokemon1)
        MainWindow.setTabOrder(self.viewPokemon1, self.listPokemon1_moves)
        MainWindow.setTabOrder(self.listPokemon1_moves, self.tabCreate)
        MainWindow.setTabOrder(self.tabCreate, self.listPokemon2_moves)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                        Pokemon 1"))
        __sortingEnabled = self.listPokemon1_moves.isSortingEnabled()
        self.listPokemon1_moves.setSortingEnabled(False)
        item = self.listPokemon1_moves.item(0)
        item.setText(_translate("MainWindow", "Move 1:"))
        item = self.listPokemon1_moves.item(1)
        item.setText(_translate("MainWindow", "Move 2: "))
        item = self.listPokemon1_moves.item(2)
        item.setText(_translate("MainWindow", "Move 3:"))
        item = self.listPokemon1_moves.item(3)
        item.setText(_translate("MainWindow", "Move 4:"))
        self.listPokemon1_moves.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "                        Battle Info:"))
        self.label_2.setText(_translate("MainWindow", "                        Pokemon 2"))
        __sortingEnabled = self.listPokemon2_moves.isSortingEnabled()
        self.listPokemon2_moves.setSortingEnabled(False)
        item = self.listPokemon2_moves.item(0)
        item.setText(_translate("MainWindow", "Move 1:"))
        item = self.listPokemon2_moves.item(1)
        item.setText(_translate("MainWindow", "Move 2: "))
        item = self.listPokemon2_moves.item(2)
        item.setText(_translate("MainWindow", "Move 3:"))
        item = self.listPokemon2_moves.item(3)
        item.setText(_translate("MainWindow", "Move 4:"))
        self.listPokemon2_moves.setSortingEnabled(__sortingEnabled)
        self.pushStartBattle.setText(_translate("MainWindow", "Start Battle"))
        self.pushRestart.setText(_translate("MainWindow", "Restart"))
        self.pushDifferentTeam.setText(_translate("MainWindow", "Choose a different team"))
        self.label_190.setText(_translate("MainWindow", "Player 1\'s team"))
        self.label_191.setText(_translate("MainWindow", "Level"))
        self.label_192.setText(_translate("MainWindow", "Level"))
        self.label_230.setText(_translate("MainWindow", "Player 2\'s team"))
        self.lbl_hpPokemon1.setText(_translate("MainWindow", "HP: "))
        self.lbl_hpPokemon2.setText(_translate("MainWindow", "HP: "))
        self.pushSwitchPlayer1.setText(_translate("MainWindow", "Switch"))
        self.pushSwitchPlayer2.setText(_translate("MainWindow", "Switch"))
        self.txtBattleInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lbl_statusPokemon1.setText(_translate("MainWindow", "Status:"))
        self.lbl_statusCond1.setText(_translate("MainWindow", "Healthy"))
        self.lbl_statusPokemon2.setText(_translate("MainWindow", "Status:"))
        self.lbl_statusCond2.setText(_translate("MainWindow", "Healthy"))
        self.tabCreate.setTabText(self.tabCreate.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Choose type of Battle</span></p></body></html>"))
        self.comboBattleType.setItemText(0, _translate("MainWindow", "1v1 Battle"))
        self.comboBattleType.setItemText(1, _translate("MainWindow", "3v3 Battle"))
        self.comboBattleType.setItemText(2, _translate("MainWindow", "6v6 Battle"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Pokemon</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">EVs</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Your Pokemon:"))
        self.label_8.setText(_translate("MainWindow", "Available Moves"))
        __sortingEnabled = self.listChosenMoves.isSortingEnabled()
        self.listChosenMoves.setSortingEnabled(False)
        item = self.listChosenMoves.item(0)
        item.setText(_translate("MainWindow", "Move 1:"))
        item = self.listChosenMoves.item(1)
        item.setText(_translate("MainWindow", "Move 2:"))
        item = self.listChosenMoves.item(2)
        item.setText(_translate("MainWindow", "Move 3:"))
        item = self.listChosenMoves.item(3)
        item.setText(_translate("MainWindow", "Move 4:"))
        self.listChosenMoves.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "Moves Chosen"))
        self.label_11.setText(_translate("MainWindow", "Level"))
        self.label_10.setText(_translate("MainWindow", "HP"))
        self.label_12.setText(_translate("MainWindow", "Attack"))
        self.label_13.setText(_translate("MainWindow", "Defense"))
        self.label_14.setText(_translate("MainWindow", "Special Attack"))
        self.label_15.setText(_translate("MainWindow", "Special Defense"))
        self.label_16.setText(_translate("MainWindow", "Speed"))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">IVs</span></p></body></html>"))
        self.label_100.setText(_translate("MainWindow", "HP"))
        self.label_101.setText(_translate("MainWindow", "Attack"))
        self.label_102.setText(_translate("MainWindow", "Defense"))
        self.label_103.setText(_translate("MainWindow", "Special Attack"))
        self.label_104.setText(_translate("MainWindow", "Special Defense"))
        self.label_127.setText(_translate("MainWindow", "Speed"))
        self.pushRandomizeEVs.setText(_translate("MainWindow", "Randomize"))
        self.pushRandomizeIVs.setText(_translate("MainWindow", "Randomize"))
        self.label_128.setText(_translate("MainWindow", "Enter Pokedex Entry"))
        self.label_129.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Final Stats</span></p></body></html>"))
        self.label_155.setText(_translate("MainWindow", "HP"))
        self.label_182.setText(_translate("MainWindow", "Attack"))
        self.label_183.setText(_translate("MainWindow", "Defense"))
        self.label_184.setText(_translate("MainWindow", "Special Attack"))
        self.label_185.setText(_translate("MainWindow", "Special Defense"))
        self.label_186.setText(_translate("MainWindow", "Speed"))
        self.label_187.setText(_translate("MainWindow", "Player 1\'s team"))
        self.label_188.setText(_translate("MainWindow", "Player 2\'s team"))
        self.pushClearP1.setText(_translate("MainWindow", "Clear"))
        self.pushClearP2.setText(_translate("MainWindow", "Clear"))
        self.pushDone.setText(_translate("MainWindow", "Done"))
        self.label_189.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Choose Player Number</span></p></body></html>"))
        self.comboPlayerNumber.setItemText(0, _translate("MainWindow", "Player 1"))
        self.comboPlayerNumber.setItemText(1, _translate("MainWindow", "Player 2"))
        self.comboPlayerNumber.setItemText(2, _translate("MainWindow", "CPU"))
        self.label_234.setText(_translate("MainWindow", "Available Abilities"))
        self.label_235.setText(_translate("MainWindow", "Nature"))
        self.comboNatures.setItemText(0, _translate("MainWindow", "Hardy"))
        self.comboNatures.setItemText(1, _translate("MainWindow", "Bold"))
        self.comboNatures.setItemText(2, _translate("MainWindow", "Modest"))
        self.comboNatures.setItemText(3, _translate("MainWindow", "Calm"))
        self.comboNatures.setItemText(4, _translate("MainWindow", "Timid"))
        self.comboNatures.setItemText(5, _translate("MainWindow", "Lonely"))
        self.comboNatures.setItemText(6, _translate("MainWindow", "Docile"))
        self.comboNatures.setItemText(7, _translate("MainWindow", "Mild"))
        self.comboNatures.setItemText(8, _translate("MainWindow", "Gentle"))
        self.comboNatures.setItemText(9, _translate("MainWindow", "Hasty"))
        self.comboNatures.setItemText(10, _translate("MainWindow", "Adamant"))
        self.comboNatures.setItemText(11, _translate("MainWindow", "Impish "))
        self.comboNatures.setItemText(12, _translate("MainWindow", "Bashful"))
        self.comboNatures.setItemText(13, _translate("MainWindow", "Careful"))
        self.comboNatures.setItemText(14, _translate("MainWindow", "Rash"))
        self.comboNatures.setItemText(15, _translate("MainWindow", "Jolly"))
        self.comboNatures.setItemText(16, _translate("MainWindow", "Naughty"))
        self.comboNatures.setItemText(17, _translate("MainWindow", "Lax"))
        self.comboNatures.setItemText(18, _translate("MainWindow", "Quirky"))
        self.comboNatures.setItemText(19, _translate("MainWindow", "Naive"))
        self.comboNatures.setItemText(20, _translate("MainWindow", "Brave"))
        self.comboNatures.setItemText(21, _translate("MainWindow", "Relaxed"))
        self.comboNatures.setItemText(22, _translate("MainWindow", "Quiet"))
        self.comboNatures.setItemText(23, _translate("MainWindow", "Sassy"))
        self.comboNatures.setItemText(24, _translate("MainWindow", "Serious"))
        self.pushFinished.setText(_translate("MainWindow", "Finished Editing"))
        self.label_239.setText(_translate("MainWindow", "Item"))
        self.pushAddMove.setText(_translate("MainWindow", "Add Move"))
        self.label_17.setText(_translate("MainWindow", "Happiness"))
        self.tabCreate.setTabText(self.tabCreate.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

